/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoreSubstrateRouteImport } from './routes/core-substrate'
import { Route as ComponentsVisuallyHiddenRouteImport } from './routes/components.visually-hidden'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreSubstrateRoute = CoreSubstrateRouteImport.update({
  id: '/core-substrate',
  path: '/core-substrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsVisuallyHiddenRoute =
  ComponentsVisuallyHiddenRouteImport.update({
    id: '/components/visually-hidden',
    path: '/components/visually-hidden',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/core-substrate': typeof CoreSubstrateRoute
  '/components/visually-hidden': typeof ComponentsVisuallyHiddenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/core-substrate': typeof CoreSubstrateRoute
  '/components/visually-hidden': typeof ComponentsVisuallyHiddenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/core-substrate': typeof CoreSubstrateRoute
  '/components/visually-hidden': typeof ComponentsVisuallyHiddenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/core-substrate' | '/components/visually-hidden'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/core-substrate' | '/components/visually-hidden'
  id: '__root__' | '/' | '/core-substrate' | '/components/visually-hidden'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoreSubstrateRoute: typeof CoreSubstrateRoute
  ComponentsVisuallyHiddenRoute: typeof ComponentsVisuallyHiddenRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-substrate': {
      id: '/core-substrate'
      path: '/core-substrate'
      fullPath: '/core-substrate'
      preLoaderRoute: typeof CoreSubstrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/visually-hidden': {
      id: '/components/visually-hidden'
      path: '/components/visually-hidden'
      fullPath: '/components/visually-hidden'
      preLoaderRoute: typeof ComponentsVisuallyHiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoreSubstrateRoute: CoreSubstrateRoute,
  ComponentsVisuallyHiddenRoute: ComponentsVisuallyHiddenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
