/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoreSubstrateRouteImport } from './routes/core-substrate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsVisuallyHiddenRouteImport } from './routes/components/visually-hidden'
import { Route as ComponentsContentPrimitivesRouteImport } from './routes/components/content-primitives'

const CoreSubstrateRoute = CoreSubstrateRouteImport.update({
  id: '/core-substrate',
  path: '/core-substrate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsVisuallyHiddenRoute =
  ComponentsVisuallyHiddenRouteImport.update({
    id: '/components/visually-hidden',
    path: '/components/visually-hidden',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsContentPrimitivesRoute =
  ComponentsContentPrimitivesRouteImport.update({
    id: '/components/content-primitives',
    path: '/components/content-primitives',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/core-substrate': typeof CoreSubstrateRoute
  '/components/content-primitives': typeof ComponentsContentPrimitivesRoute
  '/components/visually-hidden': typeof ComponentsVisuallyHiddenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/core-substrate': typeof CoreSubstrateRoute
  '/components/content-primitives': typeof ComponentsContentPrimitivesRoute
  '/components/visually-hidden': typeof ComponentsVisuallyHiddenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/core-substrate': typeof CoreSubstrateRoute
  '/components/content-primitives': typeof ComponentsContentPrimitivesRoute
  '/components/visually-hidden': typeof ComponentsVisuallyHiddenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/core-substrate'
    | '/components/content-primitives'
    | '/components/visually-hidden'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/core-substrate'
    | '/components/content-primitives'
    | '/components/visually-hidden'
  id:
    | '__root__'
    | '/'
    | '/core-substrate'
    | '/components/content-primitives'
    | '/components/visually-hidden'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoreSubstrateRoute: typeof CoreSubstrateRoute
  ComponentsContentPrimitivesRoute: typeof ComponentsContentPrimitivesRoute
  ComponentsVisuallyHiddenRoute: typeof ComponentsVisuallyHiddenRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/core-substrate': {
      id: '/core-substrate'
      path: '/core-substrate'
      fullPath: '/core-substrate'
      preLoaderRoute: typeof CoreSubstrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/visually-hidden': {
      id: '/components/visually-hidden'
      path: '/components/visually-hidden'
      fullPath: '/components/visually-hidden'
      preLoaderRoute: typeof ComponentsVisuallyHiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/content-primitives': {
      id: '/components/content-primitives'
      path: '/components/content-primitives'
      fullPath: '/components/content-primitives'
      preLoaderRoute: typeof ComponentsContentPrimitivesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoreSubstrateRoute: CoreSubstrateRoute,
  ComponentsContentPrimitivesRoute: ComponentsContentPrimitivesRoute,
  ComponentsVisuallyHiddenRoute: ComponentsVisuallyHiddenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
